global:
  scrape_interval: 15s      # Seberapa sering Prometheus menarik data secara default
  evaluation_interval: 15s  # Seberapa sering mengevaluasi rules/alerts

scrape_configs:
  # Job untuk memantau backend Bun-Hono Anda
  - job_name: 'notion_backend'
    scrape_interval: 5s     # Kita buat 5 detik agar datanya cepat terlihat saat development
    metrics_path: '/metrics' # Path default tempat metrik diekspos
    static_configs:
      - targets: ['backend:3000'] # Menggunakan nama service Docker dan port internal

# http://backend:3000/metrics